export const types = {
    //Sync
    FILL_POSTS: 'FILL_POSTS',
    CREATE_POST: 'CREATE_POST',
    CLEAR_POST: 'CLEAR_POST',
    REMOVE_POST: 'REMOVE_POST',

    //Async
    FETCH_POSTS_ASYNC:'FETCH_POSTS_ASYNC',
    CREATE_POSTS_ASYNC: 'CREATE_POSTS_ASYNC',
    REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
};