export const types = {
    //Sync
    FILL_POSTS: 'FILL_POSTS',
    CREATE_POST: 'CREATE_POST',

    //Async
    FETCH_POSTS_ASYNC:'FETCH_POSTS_ASYNC',
    CREATE_POSTS_ASYNC: 'CREATE_POSTS_ASYNC',
};