export const types = {
    // Synk
    AUTHENTICATE: 'AUTHENTICATE',
    INITIALIZE: 'INITIALIZE',
    LOGOUT: 'LOGOUT',

    // Asynk
    SYGNUP_ASYNK: 'SYGNUP_ASYNK',
    LOGIN_ASYNK: 'LOGIN_ASYNK',
    AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
    INITIALIZE_ASYNC: 'INITIALIZE_ASYNC',
    LOGOUT_ASYNC: 'LOGOUT_ASYNC',
};